---
title: "Lab 02 - Plastic waste"
author: "Insert your name here"
date: "Insert date here"
output: github_document
---

## Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
plastic_waste <- read_csv("data/plastic-waste.csv")
```

## Exercises

### Exercise 1

Trinidad

```{r plastic-waste-continent}
ggplot(data = plastic_waste, aes(x = plastic_waste_per_cap)) +
  geom_histogram(binwidth = 0.2)
```
```{r}
plastic_waste %>%
  filter(plastic_waste_per_cap > 3.5)
```
```{r}
ggplot(data = plastic_waste, aes(x = plastic_waste_per_cap)) + 
  geom_histogram(binwidth = 0.2) + 
  facet_grid(~continent)
```


### Exercise 2

```{r plastic-waste-density}

ggplot(data = plastic_waste, aes(x = plastic_waste_per_cap)) +
  geom_density()

```


### Exercise 3

```{r}
ggplot(data = plastic_waste, 
       mapping = aes(x = plastic_waste_per_cap, 
                     color = continent)) +
  geom_density()
```
```{r}
ggplot(data = plastic_waste, 
       mapping = aes(x = plastic_waste_per_cap, 
                     color = continent, 
                     fill = continent)) +
  geom_density()

```
```{r}
ggplot(data = plastic_waste, 
       mapping = aes(x = plastic_waste_per_cap, 
                     color = continent, 
                     fill = continent)) +
  geom_density(alpha = 0.2)

```
```{r}
ggplot(data = plastic_waste, 
       mapping = aes(x = continent, 
                     y = plastic_waste_per_cap)) +
  geom_boxplot()

```


### Exercise 4



```{r plastic-waste-violin}
ggplot(data = plastic_waste, aes(x = continent, y = plastic_waste_per_cap)) +
  geom_violin()

```

### Exercise 5


```{r plastic-waste-mismanaged}
ggplot(data = plastic_waste, aes(y = mismanaged_plastic_waste_per_cap, x = plastic_waste_per_cap)) +
  geom_point()
```

### Exercise 6
positive relationship

```{r plastic-waste-mismanaged-continent}
ggplot(data = plastic_waste, aes(y = mismanaged_plastic_waste_per_cap, x = plastic_waste_per_cap,
                                 color = continent)) +
  geom_point()
```

### Exercise 7


```{r plastic-waste-population-total}
ggplot(data = plastic_waste, aes(y = total_pop, x = plastic_waste_per_cap)) +
  geom_point()
```

```{r plastic-waste-population-coastal}
ggplot(data = plastic_waste, aes(y = coastal_pop, x = plastic_waste_per_cap)) +
  geom_point()
```

### Exercise 8


```{r recreate-viz}
plastic_waste %>%
  mutate(coastal_pop_prop = coastal_pop / total_pop) %>%
  filter(plastic_waste_per_cap < 3) %>%
  ggplot(aes(x = coastal_pop_prop, y = plastic_waste_per_cap)) + 
  geom_point() + 
  geom_smooth(color = "black")

```
